### ISSUE TITLE
LLNode.key should probably not be implicitly unwrapped

### ISSUE THREAD

**Issue by resuna** [waynewbishop/SwiftStructures#98]
In https://github.com/waynewbishop/SwiftStructures/blob/master/Source/Factories/LinkedList.swift LLNode.key is clearly something that can be nil, and it's explicitly checked before use. It should probably be T? and explicitly unwrapped in the few cases where it needs to be.

**Comment by waynewbishop** [comment]
Thanks @resuna for sending along this code issue! Since your original request, the book has been updated with the majority of implicit unwrapped optional values changed or removed. See the latest version at:

https://shop.waynewbishop.com/collections/2017-swift-algorithms-catalog/products/swift-algorithms-3rd-edition
